### ISSUE TITLE
Release 1.0b1?

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.js.cycle2#5]

**Comment by hvelarde** [comment]
@djowett @fredvd @rodfersou please review latest changes. 

can I make a release now?

**Comment by djowett** [comment]
I prefer keeping my files in the JS registry to be honest, but it seems there are differing opinions.  I just wanted to highlight this well written paragraph from [Plone docs](http://docs.plone.org/external/plone.app.dexterity/docs/advanced/static-resources.html#registering-resources-with-plones-resource-registries) on the subject to make sure you are aware of it....

> It may seem wasteful to include a resource that is not be used on all pages in the global registry. Remember, however, that portal_css and portal_javascripts will merge and compress resources, and set caching headers such that browsers and caching proxies can cache resources well. It is often more effective to have one slightly larger file that caches well, than to have a variable number of files that may need to be loaded at different times.

... but I do admit the paragraphs above show the technique you are adopting as well, though I don't know which technique is older / more favoured.  Also note, using the JS registry means not having to worry about _changing templates_ - which I think you wanted to avoid users having to change, yes?

IF you _do_ go through with the change, then you would want to delete lines 50 - 52 of README.rst

**Comment by rodfersou** [comment]
@djowett good job highlighting this paragraph from Plone docs, I wasn't aware of it.

But the point here is if the "collective.js.something packages" should be the right place to register the resources.

Maybe into this package we could add just the minimum JS needed to make new control panel options work since this package will provide the global configurations, but I don't think every package will need everything JS file, and if needed that file should be registered in the package that will use it.

My point was that before this package didn't use the registered JS resources, it was used by other packages, and I saw a problem with center plugin.

I know that was a wrong configuration mine, but was it really necessary to center stuff with JS? CSS is the layer responsible to do design stuff, not JS, and this is one of the best thing about cycle2 in comparison with galleria, it can be styled with CSS in a better way.

**Comment by hvelarde** [comment]
@djowett nothing prevents you from adding resources into the Plone registry; what we are trying to do here is just give freedom to the developer/integrator on which plugins to include as we provide all of them and it would be a bad idea to add them to the registry if they are not going to be used.

IMO, the Plone documentation is almost right; the main problem here is the update of the JS code: if you're setting your cache too strong then the proxy have no way to know that the code has changed and it will continue serving the old cached code. Plone's resource registries solve that by creating a unique name for the merged resources each time you cook them, so the code will always be the latest one assuming you don't forget to do so.

I was checking at the Zope response headers and seems to me they are fine and worst case scenario is having one request only for each new client:

![selection_001](https://cloud.githubusercontent.com/assets/341393/7844089/5ba46ba2-0484-11e5-8cf0-d76e324da758.png)

seems to me we can have the beta release as soon as I fix the README as per your suggestion.

**Comment by hvelarde** [comment]
released: https://pypi.python.org/pypi/collective.js.cycle2/1.0b1

**Comment by djowett** [comment]
I really love the way the JS & CSS registries handle caching in Plone4, I hope that doesn't go away in Plone 5.

@rodfersou you said:

> ... but was it really necessary to center stuff with JS? CSS is the layer responsible to do design stuff, not JS....
> I think you'll find that _vertical_ centering is near impossible in pure CSS - especially with multiple differently sized images in a slideshow to centre consistently.  I think galleria also uses JS for vertical centering.

**Comment by hvelarde** [comment]
@djowett there are some changes that I haven't had time to review yet: http://www.nathanvangheem.com/news/plone-5-resource-registries

**Comment by rodfersou** [comment]
@djowett I was referring to the JS center plugin
